#
#   Builds the RPM and keeps the ZIP
#

name: Build Packages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - 'assets/**'
      - 'TODO'
  
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build RPM and DEB packages
        run: |
          make

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: video-gadgets
          path: |
            dist/video-gadgets-*.noarch.rpm
            dist/video-gadgets_*.deb
            dist/video-gadgets-*.tgz
          retention-days: 14

